#!/bin/bash -eu

if [ "$BASH_SOURCE" != "$0" ]
then
  echo "$BASH_SOURCE must be executed, not sourced"
  return 1 # shouldn't use exit when sourced
fi

if [ "${FLOCKED:-}" != "$0" ]
then
  if FLOCKED="$0" flock -en -E 99 "$0" "$0" "$@" || case "$?" in
  99) echo already running
      exit 99
      ;;
  *)  exit $?
      ;;
  esac
  then
    # success
    exit 0
  fi
fi

REPO=${REPO:-ElJeffe}
BRANCH=${BRANCH:-main-dev}
HEADLESS_SETUP=${HEADLESS_SETUP:-false}
USE_LED_FOR_SETUP_PROGRESS=true
CONFIGURE_ARCHIVING=${CONFIGURE_ARCHIVING:-true}
UPGRADE_PACKAGES=${UPGRADE_PACKAGES:-true}
TESLAUSB_HOSTNAME=${TESLAUSB_HOSTNAME:-teslausb}
SETUP_ACCESS_POINT=${SETUP_ACCESS_POINT:-true}
export camsize=${camsize:-100%}
export musicsize=${musicsize:-100%}
export INSTALL_DIR=${INSTALL_DIR:-/bin}

function setup_progress () {
  local setup_logfile=/boot/teslausb-headless-setup.log
  if [ $HEADLESS_SETUP = "true" ]
  then
    echo "$( date ) : $1" >> "$setup_logfile"
  fi
  echo $1
}

if ! [ $(id -u) = 0 ]
then
  setup_progress "STOP: Run sudo -i."
  exit 1
fi

function headless_setup_populate_variables () {
  # Pull in the conf file variables to make avail to this script and subscripts
  # If setup-teslausb is run from rc.local, the conf file will have been moved
  # to /root by rc.local
  if [ $HEADLESS_SETUP = "true" ]
  then
    if [ -e /boot/teslausb_setup_variables.conf ]
    then
      setup_progress "reading config from /boot/teslausb_setup_variables.conf"
      source /boot/teslausb_setup_variables.conf
    elif [ -e /root/teslausb_setup_variables.conf ]
    then
      setup_progress "reading config from /root/teslausb_setup_variables.conf"
      source /root/teslausb_setup_variables.conf
    else
      setup_progress "couldn't find config file"
    fi
  fi
}

function headless_setup_mark_setup_success () {
  if [ $HEADLESS_SETUP = "true" ]
  then

    if [ -e /boot/TESLAUSB_SETUP_FAILED ]
    then
      rm /boot/TESLAUSB_SETUP_FAILED
    fi

    rm -f /boot/TESLAUSB_SETUP_STARTED
    touch /boot/TESLAUSB_SETUP_FINISHED
    setup_progress "Main setup completed."
  fi
}

function headless_setup_progress_flash () {
  if [ $USE_LED_FOR_SETUP_PROGRESS = "true" ] && [ $HEADLESS_SETUP = "true" ]
  then
    /etc/stage_flash $1
  fi
}

function setup_led_off () {

  if [ $USE_LED_FOR_SETUP_PROGRESS = "true" ] && [ $HEADLESS_SETUP = "true" ]
  then
    echo "none" | sudo tee /sys/class/leds/led0/trigger > /dev/null
    echo 1 | sudo tee /sys/class/leds/led0/brightness > /dev/null
  fi
}

function setup_led_on () {

  if [ $USE_LED_FOR_SETUP_PROGRESS = "true" ] && [ $HEADLESS_SETUP = "true" ]
  then
    echo 0 | sudo tee /sys/class/leds/led0/brightness > /dev/null
  fi
}

function verify_configuration () {
  get_script /tmp verify-configuration.sh setup/pi
  
  /tmp/verify-configuration.sh
}

function get_script () {
  local local_path="$1"
  local name="$2"
  local remote_path="${3:-}"
  
  curl --fail -o "$local_path/$name" https://raw.githubusercontent.com/"$REPO"/teslausb/"$BRANCH"/"$remote_path"/"$name"
  # wget -O "$local_path/$name" https://raw.githubusercontent.com/"$REPO"/teslausb/"$BRANCH"/"$remote_path"/"$name"
  chmod +x "$local_path/$name"
  setup_progress "Downloaded $local_path/$name ..."
}

function get_ancillary_setup_scripts () {
  get_script /tmp create-backingfiles-partition.sh setup/pi
  get_script /tmp create-backingfiles.sh setup/pi
  get_script /tmp make-root-fs-readonly.sh setup/pi
  get_script /root configure.sh setup/pi
}

function fix_cmdline_txt_modules_load ()
{
  setup_progress "Fixing the modules-load parameter in /boot/cmdline.txt..."
  cp /boot/cmdline.txt ~
  cat ~/cmdline.txt | sed 's/ modules-load=dwc2,g_ether/ modules-load=dwc2/' > /boot/cmdline.txt
  rm ~/cmdline.txt
  setup_progress "Fixed cmdline.txt."
}

BACKINGFILES_MOUNTPOINT=/backingfiles
MUTABLE_MOUNTPOINT=/mutable

function create_usb_drive_backing_files () {
  if [ ! -e "$BACKINGFILES_MOUNTPOINT" ]
  then
    mkdir "$BACKINGFILES_MOUNTPOINT"
  fi

  if [ ! -e "$MUTABLE_MOUNTPOINT" ]
  then
    mkdir "$MUTABLE_MOUNTPOINT"
  fi
  
  if ! blkid -L backingfiles
  then
    setup_progress "Starting to create backing files partition..."
    /tmp/create-backingfiles-partition.sh "$BACKINGFILES_MOUNTPOINT" "$MUTABLE_MOUNTPOINT"
  fi
  
  if ! findmnt --mountpoint $BACKINGFILES_MOUNTPOINT
  then
    setup_progress "Mounting the partition for the backing files..."
    mount $BACKINGFILES_MOUNTPOINT
    setup_progress "Mounted the partition for the backing files."
  fi

  if [ ! -e $BACKINGFILES_MOUNTPOINT/cam_disk.bin ]
  then
    setup_progress "Creating backing disk files."
    /tmp/create-backingfiles.sh "$camsize" "$musicsize" "$BACKINGFILES_MOUNTPOINT"
  fi
}

function configure_hostname () {
  # Headless image already has hostname set
  if [ ! $HEADLESS_SETUP = "true" ]
  then
    setup_progress "Configuring the hostname..."

    local new_host_name="$TESLAUSB_HOSTNAME"
    cp /etc/hosts ~
    sed "s/raspberrypi/$new_host_name/g" ~/hosts > /etc/hosts
    rm ~/hosts

    cp /etc/hostname ~
    sed "s/raspberrypi/$new_host_name/g" ~/hostname > /etc/hostname
    setup_progress "Configured the hostname."
    rm ~/hostname
  fi
}

function make_root_fs_readonly () {
  /tmp/make-root-fs-readonly.sh
}

function update_package_index () {
  setup_progress "Updating package index files..."
    if [ "$UPGRADE_PACKAGES" = true ]
    then
      apt-get update
    fi
}

function install_packages () {
  apt-get install -y btrfs-tools vim
  apt-get purge -y bluez
  apt-get autoremove -y --purge
}

function upgrade_packages () {
  if [ "$UPGRADE_PACKAGES" = true ]
  then
    setup_progress "Upgrading installed packages..."
    apt-get --assume-yes upgrade
  else
    setup_progress "Skipping package upgrade."
  fi
}

function set_timezone () {
  if [ ! -z ${timezone:+x} ]
  then
    if [ -f "/usr/share/zoneinfo/$timezone" ]
    then
      ln -sf "/usr/share/zoneinfo/$timezone" /etc/localtime
    elif [ "$timezone" = "auto" ]
    then
      if curl -o /root/bin/tzupdate.py https://raw.githubusercontent.com/marcone/tzupdate/develop/tzupdate.py
      then
        apt-get -y --force-yes install python-requests
        chmod +x /root/bin/tzupdate.py
        if ! tzout=$(/root/bin/tzupdate.py 2>&1)
        then
          setup_progress "auto timezone failed: $tzout"
        else
          setup_progress "$tzout"
        fi
      fi
    else
      setup_progress "invalid timezone: $timezone"
    fi
  fi
}


function install_rc_local () {
    local install_home="$1"

    if grep -q archiveloop /etc/rc.local
    then
        setup_progress "Skipping rc.local installation"
        return
    fi

    setup_progress "Configuring /etc/rc.local to run the archive scripts at startup..."
    echo "#!/bin/bash -eu" > ~/rc.local
    echo "install_home=\"${install_home}\"" >> ~/rc.local
    cat << 'EOF' >> ~/rc.local
LOGFILE=/tmp/rc.local.log

function log () {
  echo "$( date )" >> "$LOGFILE"
  echo "$1" >> "$LOGFILE"
}

log "Launching archival script..."
"$install_home"/archiveloop &
log "All done"
exit 0
EOF

    cat ~/rc.local > /etc/rc.local
    rm ~/rc.local
    setup_progress "Installed rc.local."
}

function configure_init_scripts() {
  get_script $INSTALL_DIR archiveloop run
  get_script $INSTALL_DIR remountfs_rw run
  get_script $INSTALL_DIR usbmount run

  install_rc_local INSTALL_DIR
}

function install_services() {
  get_script /etc/systemd/system usbmount.service run/services
  systemctl enable usbmount
  systemctl enable ssh
}

function setup_access_point() {
  apt-get install -y dnsmasq hostapd lighttpd php7.0-fpm

    setup_progress "configure static IP" 
  if ! grep -q "^interface wlan0" /etc/dhcpcd.conf
  then
    setup_progress "Update /etc/dhcpcd.conf"
    cat <<EOT >> /etc/dhcpcd.conf
interface wlan0
    nohook wpa_supplicant
EOT
  fi

  setup_progress "Configure DHCP server"
  if ! grep -q "^interface=wlan0" /etc/dnsmasq.conf
  then
    setup_progress "Update /etc/dnsmasq.conf"
    mv /etc/dnsmasq.conf /etc/dnsmasq.conf.orig
    cat <<EOT >> /etc/dnsmasq.conf
interface=wlan0
dhcp-range=192.168.4.2,192.168.4.20,255.255.255.0,24h
listen-address=192.168.4.1
addn-hosts=/etc/fake.hosts
EOT
    cat <<EOT > /etc/fake.hosts
192.168.4.1     teslacam.com
EOT
  fi

  setup_progress "Configure hostapd"
  if ! grep -q "^interface=wlan0" /etc/hostapd/hostapd.conf
  then
    setup_progress "Update /etc/hostapd/hostapd.conf"
    cat <<EOT >> /etc/hostapd/hostapd.conf
interface=wlan0
driver=nl80211
ssid=Cam
hw_mode=g
channel=7
wmm_enabled=0
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=ElonMusk
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0
EOT
  fi
  echo "Update /etc/default/hostapd"
  sed -i 's/^#DAEMON_CONF.*$/DAEMON_CONF="\/etc\/hostapd\/hostapd.conf"/g' /etc/default/hostapd

  echo "configure web server"
  get_script /etc/lighttpd lighttpd.conf run/etc
  ln -s ../conf-available/10-fastcgi.conf /etc/lighttpd/conf-enabled
  ln -s ../conf-available/15-fastcgi-php.conf /etc/lighttpd/conf-enabled
  get_script /etc/lighttpd/conf-available 15-fastcgi-php.conf run/etc
  wget https://release.larsjung.de/h5ai/h5ai-0.29.2.zip -O /tmp/h5ai.zip
  unzip /tmp/h5ai.zip -d /var/www/html/
  ln -s /mnt/cam/TeslaCam /var/www/html/TeslaCam
  rm /var/www/html/index.lighttpd.html
  systemctl disable wpa_supplicant
  systemctl unmask hostapd
  systemctl disable hostapd
  systemctl enable dnsmasq
}

export -f setup_progress
export HEADLESS_SETUP

update_package_index

install_packages

headless_setup_populate_variables

# If USE_LED_FOR_SETUP_PROGRESS = true. 
setup_led_off

# set time zone so we get decent timestamps in the rest of the setup log
set_timezone

# Flash for stage 2 headless (verify requested configuration)
headless_setup_progress_flash 1

setup_progress "Verifying that the requested configuration is valid..."

verify_configuration

# Flash for Stage 3 headless (grab scripts)
headless_setup_progress_flash 2

setup_progress "Downloading additional setup scripts."

get_ancillary_setup_scripts

pushd ~

fix_cmdline_txt_modules_load

# Flash for stage 4 headless (Create backing files)
headless_setup_progress_flash 3

create_usb_drive_backing_files

configure_hostname

# Flash for stage 5 headless (Mark success, FS readonly)
headless_setup_progress_flash 4

headless_setup_mark_setup_success

install_services

if [ "$SETUP_ACCESS_POINT" = true ]
then
  setup_access_point
fi

if [ "$CONFIGURE_ARCHIVING" = true ]
then
  setup_progress "calling configure.sh"
  /root/configure.sh
else
  setup_progress "skipping configure.sh"
fi

configure_init_scripts

make_root_fs_readonly

upgrade_packages

# If USE_LED_FOR_SETUP_PROGRESS = true. 
setup_led_on

setup_progress "All done."
